## in EDA what things we do
1. Missing Value
2. Explore about the num var
3. Explore about the categorical var
4. Finding Relationships between features

# Types of data values
int64 means integer variable, object means categorical variable/text data/int variable, float64 means floating values.

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

using isnull.sum() we can see that there are no null values in any column is this dataset

# basic structure for a dataset:
1. df.shape : tells the no. of (rows,columns).
2. df.head() : fetches the first 5 records.
3. df.tail() : fetches the last 5 records.
4. df.info() : gives infoo about the dataset.
5. df.describe() : tells us meaningful info about the data ex. mean,max,min,median.
6. df.columns : no. of columns.
7. df.dtypes : tells the data type.
8. df.nunique(): tells about unique values in each column.

# Accessing Data with Pandas
1. df
2. df.loc[start:end] : used to fetch the records or rows or also we an write df.loc[3:9,"column name"]
3. df.index

In [49]:
df = pd.read_csv("Heart.csv")

In [50]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [51]:
df.shape

(918, 12)

In [52]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [54]:
df.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1

In [57]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [59]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
913    False
914    False
915    False
916    False
917    False
Length: 918, dtype: bool

In [60]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [61]:
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [67]:
df["ChestPainType"].value_counts()

ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

In [64]:
df["Sex"].value_counts()

Sex
M    725
F    193
Name: count, dtype: int64

In [68]:
df["ExerciseAngina"].value_counts()

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64

In [69]:
df["RestingECG"].value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [70]:
df["ST_Slope"].value_counts()

ST_Slope
Flat    460
Up      395
Down     63
Name: count, dtype: int64

# Interpretation
1. Sex : M is more common
2. ChestPainType : ASY is much more common than TA
3. ST_Slope : down is more common than flat/up
4. min cholesterol is 0 which is unlikely!!
5. restingBP is also 0 which is unusual!!

In [79]:
(df["RestingBP"]==0).sum()
df[df["RestingBP"]==0]["HeartDisease"].value_counts()

HeartDisease
1    1
Name: count, dtype: int64

In [78]:
(df["Cholesterol"]==0).sum()
df[df["Cholesterol"]==0]["HeartDisease"].value_counts()

HeartDisease
1    152
0     20
Name: count, dtype: int64